--맛집 테이블(사이트에서 등록하는 것)

CREATE TABLE EAT_RESTAURANT(
	SEQ NUMBER PRIMARY KEY,
	RS_NAME VARCHAR2(100) UNIQUE,
	RS_ADDRESS1 VARCHAR2(200) NOT NULL,
	RS_ADDRESS2 VARCHAR2(100) NOT NULL,
	RS_PICTURE VARCHAR2(100) NOT NULL,
	RS_CATEGORY VARCHAR2(100) NOT NULL,
	RS_MENU VARCHAR2(4000) NOT NULL,
	RS_MENU VARCHAR2(4000),
	RS_RATING NUMBER NOT NULL,
	RS_READCOUNT NUMBER NOT NULL
	
);

alter table eat_restaurant add (rs_keyword varchar2(4000));

alter table eat_restaurant modify (rs_menu varchar2(4000));

select * from eat_restaurant
select * from restaurant_review

--맛집 정보
CREATE TABLE RESTAURANT_INFO(
	RS_NAME VARCHAR2(100) NOT NULL, --맛집 이름
	RS_SEQ NUMBER NOT NULL, --맛집 번호
	RS_TIME VARCHAR2(100), --영업시간
	RS_PHONE VARCHAR2(100), --전화번호
	RS_PRICE VARCHAR2(100), --가격대
	RS_PARKING NUMBER --주차 여부

);

ALTER TABLE RESTAURANT_INFO --맛집 이름을 외래키로 넘겨받음
   ADD CONSTRAINT INFO_NAME_FK 
   FOREIGN KEY (RS_NAME) REFERENCES EAT_RESTAURANT (RS_NAME) ON DELETE CASCADE
   
ALTER TABLE RESTAURANT_INFO --맛집의 번호를 외래키로 넘겨받음
   ADD CONSTRAINT INFO_NUMBER_FK
   FOREIGN KEY (RS_SEQ) REFERENCES EAT_RESTAURANT (SEQ) ON DELETE CASCADE
   
   
--맛집 리뷰 테이블
CREATE TABLE RESTAURANT_REVIEW(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	RS_SEQ NUMBER NOT NULL,
	RS_CONTENT CLOB NOT NULL,
	RS_PICTURE CLOB,
	RS_RATING NUMBER NOT NULL
);
CREATE SEQUENCE REIVEW_SEQ
   START WITH 1 INCREMENT BY 1
   
ALTER TABLE RESTAURANT_REVIEW --멤버 ID 외래키로 넘겨받음
   ADD CONSTRAINT REVIEW_ID_FK
   FOREIGN KEY (ID) REFERENCES EATMEMBER (ID) ON DELETE CASCADE
   
ALTER TABLE RESTAURANT_REVIEW
   ADD CONSTRAINT REVIEW_SEQ_FK--맛집 번호 외래키로 넘겨받음
   FOREIGN KEY (SEQ) REFERENCES EAT_RESTAURANT (SEQ) ON DELETE CASCADE

--가고싶다 테이블
CREATE TABLE RESTAURANT_LIKES(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	RS_SEQ NUMBER NOT NULL,
	RS_NAME VARCHAR2(100) NOT NULL

);

CREATE SEQUENCE LIKES_SEQ
	START WITH 1 INCREMENT BY 1;
	
ALTER TABLE RESTAURANT_LIKES --멤버 ID 외래키로 넘겨받음
   ADD CONSTRAINT LIKES_ID_FK
   FOREIGN KEY (ID) REFERENCES EATMEMBER (ID) ON DELETE CASCADE
   
ALTER TABLE RESTAURANT_LIKES
   ADD CONSTRAINT LIKES_SEQ_FK--맛집 번호 외래키로 넘겨받음
   FOREIGN KEY (SEQ) REFERENCES EAT_RESTAURANT (SEQ) ON DELETE CASCADE